services:
  backend:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    working_dir: /workspace/backend/Api
    volumes:
      - ..:/workspace:cached
    ports:
      - "5000:5000"
    command: sh -c "dotnet restore && dotnet run --no-launch-profile"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000

  frontend:
    image: node:20-alpine
    working_dir: /workspace/frontend
    volumes:
      - ..:/workspace:cached
    ports:
      - "0.0.0.0:5174:5174"
    environment:
      - WATCHPACK_POLLING=true
      - VITE_API_URL=http://10.150.5.65:5000
    command: sh -c "VITE_API_URL=http://10.150.5.65:5000 npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend
