services:
  backend:
    build:
      context: ./backend
      dockerfile: Api/Dockerfile
    ports:
      - "5020:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5000
      ConnectionStrings__DefaultConnection: Host=${REMOTE_DB_HOST};Port=${REMOTE_DB_PORT};Username=${REMOTE_DB_USER};Password=${REMOTE_DB_PASSWORD};Database=${REMOTE_DB_NAME};

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    environment:
      VITE_API_URL: http://192.168.155.144:5020
      VITE_PROXY_TARGET: http://backend:5001
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules