version: '3.8'

services:
  backend:
    build:
      context: ./backend/Api
      dockerfile: Dockerfile
    ports:
      - "5020:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0
      - ConnectionStrings__DefaultConnection=Host=${REMOTE_DB_HOST};Port=${REMOTE_DB_PORT};Database=${REMOTE_DB_NAME};Username=${REMOTE_DB_USER};Password=${REMOTE_DB_PASSWORD};

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    environment:
      - VITE_API_URL=http://localhost:5020
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

