using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace VehicleBook.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class CreateFullSupabaseSchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
-- =========================================================
-- FleetPro full Supabase PostgreSQL schema
-- Creates/syncs the main tables used by the backend:
-- users, vehicles, bookings, notifications, bookingaudit
-- =========================================================

-- Vehicle availability enum used by vehicles.isavailable
DO $$
BEGIN
    CREATE TYPE public.status_type AS ENUM ('Available', 'Unavailable');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- Users
CREATE TABLE IF NOT EXISTS public.users (
    userid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(50) NOT NULL,
    email character varying(50) NOT NULL,
    phone character varying(20) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(20) NOT NULL DEFAULT 'Guest',
    refreshtoken character varying(255),
    refreshtokenexpirytime date,
    lastlogin timestamp with time zone
);

ALTER TABLE public.users ADD COLUMN IF NOT EXISTS name character varying(50) NOT NULL DEFAULT '';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS email character varying(50) NOT NULL DEFAULT '';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS phone character varying(20) NOT NULL DEFAULT '';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS password character varying(255) NOT NULL DEFAULT '';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS role character varying(20) NOT NULL DEFAULT 'Guest';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS refreshtoken character varying(255);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS refreshtokenexpirytime date;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS lastlogin timestamp with time zone;

ALTER TABLE public.users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE public.users ADD CONSTRAINT users_role_check
CHECK (role = ANY (ARRAY['Guest', 'Company', 'Owner', 'Admin']::text[]));

CREATE UNIQUE INDEX IF NOT EXISTS users_email_key ON public.users (email);

-- Vehicles
CREATE TABLE IF NOT EXISTS public.vehicles (
    vehicleid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ownerid integer NOT NULL,
    make character varying(120) NOT NULL,
    model character varying(120) NOT NULL,
    category character varying(50) NOT NULL DEFAULT 'Sedan',
    dailyrate numeric(10,2) NOT NULL,
    isavailable public.status_type NOT NULL DEFAULT 'Available'::public.status_type,
    licensenumber character varying(20) NOT NULL DEFAULT '',
    vinnumber character varying(50) NOT NULL DEFAULT '',
    modelyear integer NOT NULL DEFAULT 0
);

ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS ownerid integer NOT NULL DEFAULT 0;
ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS make character varying(120) NOT NULL DEFAULT '';
ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS model character varying(120) NOT NULL DEFAULT '';
ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS category character varying(50) NOT NULL DEFAULT 'Sedan';
ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS dailyrate numeric(10,2) NOT NULL DEFAULT 0;
ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS isavailable public.status_type NOT NULL DEFAULT 'Available'::public.status_type;
ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS licensenumber character varying(20) NOT NULL DEFAULT '';
ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS vinnumber character varying(50) NOT NULL DEFAULT '';
ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS modelyear integer NOT NULL DEFAULT 0;

ALTER TABLE public.vehicles DROP CONSTRAINT IF EXISTS vehicles_category_check;
ALTER TABLE public.vehicles ADD CONSTRAINT vehicles_category_check
CHECK (category = ANY (ARRAY['Sedan', 'Hatchback', 'SUV', 'Convertible', 'Pickup Truck', 'Minivan/MPV']::text[]));

CREATE INDEX IF NOT EXISTS ix_vehicles_ownerid ON public.vehicles (ownerid);

-- Bookings
CREATE TABLE IF NOT EXISTS public.bookings (
    bookingid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    companyid integer NOT NULL,
    vehicleid integer NOT NULL,
    licensenumber character varying(20) NOT NULL DEFAULT '',
    startdate date NOT NULL,
    enddate date NOT NULL,
    totalcost numeric(10,2) NOT NULL,
    status character varying(20) NOT NULL DEFAULT 'Pending'
);

ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS companyid integer NOT NULL DEFAULT 0;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS vehicleid integer NOT NULL DEFAULT 0;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS licensenumber character varying(20) NOT NULL DEFAULT '';
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS startdate date NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS enddate date NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS totalcost numeric(10,2) NOT NULL DEFAULT 0;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS status character varying(20) NOT NULL DEFAULT 'Pending';

ALTER TABLE public.bookings DROP CONSTRAINT IF EXISTS bookings_status_check;
ALTER TABLE public.bookings ADD CONSTRAINT bookings_status_check
CHECK (status = ANY (ARRAY['Pending', 'Confirmed', 'Approved', 'Rejected', 'Cancelled', 'Completed']::text[]));

CREATE INDEX IF NOT EXISTS ix_bookings_companyid ON public.bookings (companyid);
CREATE INDEX IF NOT EXISTS ix_bookings_vehicleid ON public.bookings (vehicleid);

-- Notifications
CREATE TABLE IF NOT EXISTS public.notifications (
    notificationid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userid integer NOT NULL,
    title character varying(150) NOT NULL,
    message text NOT NULL,
    type character varying(50) NOT NULL DEFAULT 'General',
    entitytype character varying(50),
    entityid integer,
    isread boolean NOT NULL DEFAULT false,
    createdatutc timestamp with time zone NOT NULL DEFAULT NOW(),
    readatutc timestamp with time zone
);

ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS userid integer NOT NULL DEFAULT 0;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS title character varying(150) NOT NULL DEFAULT '';
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS message text NOT NULL DEFAULT '';
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS type character varying(50) NOT NULL DEFAULT 'General';
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS entitytype character varying(50);
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS entityid integer;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS isread boolean NOT NULL DEFAULT false;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS createdatutc timestamp with time zone NOT NULL DEFAULT NOW();
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS readatutc timestamp with time zone;

CREATE INDEX IF NOT EXISTS ix_notifications_userid ON public.notifications (userid);

-- Booking audit/outbox table for RabbitMQ publishing
CREATE TABLE IF NOT EXISTS public.bookingaudit (
    auditid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bookingid integer NOT NULL,
    companyid integer,
    vehicleid integer,
    oldstatus character varying(20),
    newstatus character varying(20) NOT NULL,
    eventtype character varying(100) NOT NULL DEFAULT 'BookingStatusChanged',
    message text,
    ispublished boolean NOT NULL DEFAULT false,
    publishedat timestamp with time zone,
    createdat timestamp with time zone NOT NULL DEFAULT NOW()
);

ALTER TABLE public.bookingaudit ADD COLUMN IF NOT EXISTS bookingid integer NOT NULL DEFAULT 0;
ALTER TABLE public.bookingaudit ADD COLUMN IF NOT EXISTS companyid integer;
ALTER TABLE public.bookingaudit ADD COLUMN IF NOT EXISTS vehicleid integer;
ALTER TABLE public.bookingaudit ADD COLUMN IF NOT EXISTS oldstatus character varying(20);
ALTER TABLE public.bookingaudit ADD COLUMN IF NOT EXISTS newstatus character varying(20) NOT NULL DEFAULT 'Pending';
ALTER TABLE public.bookingaudit ADD COLUMN IF NOT EXISTS eventtype character varying(100) NOT NULL DEFAULT 'BookingStatusChanged';
ALTER TABLE public.bookingaudit ADD COLUMN IF NOT EXISTS message text;
ALTER TABLE public.bookingaudit ADD COLUMN IF NOT EXISTS ispublished boolean NOT NULL DEFAULT false;
ALTER TABLE public.bookingaudit ADD COLUMN IF NOT EXISTS publishedat timestamp with time zone;
ALTER TABLE public.bookingaudit ADD COLUMN IF NOT EXISTS createdat timestamp with time zone NOT NULL DEFAULT NOW();

ALTER TABLE public.bookingaudit DROP CONSTRAINT IF EXISTS bookingaudit_status_check;
ALTER TABLE public.bookingaudit ADD CONSTRAINT bookingaudit_status_check
CHECK (
    (oldstatus IS NULL OR oldstatus = ANY (ARRAY['Pending', 'Confirmed', 'Approved', 'Rejected', 'Cancelled', 'Completed']::text[]))
    AND newstatus = ANY (ARRAY['Pending', 'Confirmed', 'Approved', 'Rejected', 'Cancelled', 'Completed']::text[])
);

CREATE INDEX IF NOT EXISTS ix_bookingaudit_ispublished_createdat ON public.bookingaudit (ispublished, createdat);

-- Foreign keys. These are wrapped so existing constraints do not break the script.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'vehicles_ownerid_fkey') THEN
        ALTER TABLE public.vehicles
        ADD CONSTRAINT vehicles_ownerid_fkey
        FOREIGN KEY (ownerid) REFERENCES public.users(userid)
        ON DELETE NO ACTION NOT VALID;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'bookings_companyid_fkey') THEN
        ALTER TABLE public.bookings
        ADD CONSTRAINT bookings_companyid_fkey
        FOREIGN KEY (companyid) REFERENCES public.users(userid)
        ON DELETE NO ACTION NOT VALID;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'bookings_vehicleid_fkey') THEN
        ALTER TABLE public.bookings
        ADD CONSTRAINT bookings_vehicleid_fkey
        FOREIGN KEY (vehicleid) REFERENCES public.vehicles(vehicleid)
        ON DELETE NO ACTION NOT VALID;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notifications_userid_fkey') THEN
        ALTER TABLE public.notifications
        ADD CONSTRAINT notifications_userid_fkey
        FOREIGN KEY (userid) REFERENCES public.users(userid)
        ON DELETE CASCADE NOT VALID;
    END IF;
END $$;
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
DROP TABLE IF EXISTS public.bookingaudit;
DROP TABLE IF EXISTS public.notifications;
DROP TABLE IF EXISTS public.bookings;
DROP TABLE IF EXISTS public.vehicles;
DROP TABLE IF EXISTS public.users;
DROP TYPE IF EXISTS public.status_type;
");
        }
    }
}
